/**
 * Fonte única de definição de temas (light e dark).
 * Valores são usados para gerar app/theme-generated.css via npm run generate:themes.
 * Variáveis que usam var(--...) dependem de outras do mesmo tema: secondary, info, surface-2, surface-3, radius, sparkline-*.
 * As escalas semânticas (primary/destructive/success/neutrals) ficam disponíveis
 * para uso futuro sem quebrar os aliases semânticos já consumidos pelo app.
 */
export type ThemeVars = Record<string, string>;

/** Ordem das variáveis CSS para saída consistente (todo tema deve definir estas chaves). */
export const THEME_VAR_NAMES: readonly string[] = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "neutral-chroma",
  "neutral-hue",
  "neutral-950",
  "neutral-800",
  "neutral-600",
  "neutral-400",
  "surface-fill",
  "primary-950",
  "primary-800",
  "primary-600",
  "primary-400",
  "primary-300",
  "primary-label",
  "destructive-950",
  "destructive-800",
  "destructive-600",
  "destructive-400",
  "destructive-300",
  "destructive-label",
  "success-950",
  "success-800",
  "success-600",
  "success-400",
  "success-300",
  "success-label",
  "primary",
  "primary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "success",
  "success-foreground",
  "warning",
  "warning-foreground",
  "info",
  "info-foreground",
  "attention",
  "attention-foreground",
  "input",
  "input-foreground",
  "border",
  "ring",
  "ring-foreground",
  "sidebar",
  "sidebar-foreground",
  "sidebar-foreground-rgb",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "level-0",
  "level-1",
  "level-2",
  "level-3",
  "level-4",
  "surface",
  "surface-2",
  "surface-3",
  "radius-sm",
  "radius-md",
  "radius-lg",
  "radius",
  "overlay",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "sparkline-red",
  "sparkline-orange",
  "sparkline-yellow",
  "sparkline-green",
  "sparkline-blue",
  "sparkline-muted",
] as const;

const semanticScaleTokens: ThemeVars = {
  // TEMPERATURA DO CINZA — os dois valores abaixo tingem toda a rampa de neutros e os
  // cinco niveis de superficie. Croma 0,007 no matiz 265 (o do azul da marca) = "frio
  // sutil", decidido em 2026-09-16 comparando neutro, frio e quente lado a lado. Para
  // voltar ao cinza puro: neutral-chroma = 0.
  "neutral-chroma": "0.007",
  "neutral-hue": "265.0",
  "neutral-950": "oklch(0.209 var(--neutral-chroma) var(--neutral-hue))",
  "neutral-800": "oklch(0.348 var(--neutral-chroma) var(--neutral-hue))",
  "neutral-600": "oklch(0.524 var(--neutral-chroma) var(--neutral-hue))",
  "neutral-400": "oklch(0.715 var(--neutral-chroma) var(--neutral-hue))",
  "surface-fill": "oklch(0.967 calc(var(--neutral-chroma) / 2) var(--neutral-hue))",
  "primary-950": "oklch(0.210 0.080 265.9)",
  "primary-800": "oklch(0.411 0.171 264.9)",
  "primary-600": "oklch(0.561 0.244 265.2)",
  "primary-400": "oklch(0.662 0.180 258.7)",
  "primary-300": "oklch(0.779 0.113 241.5)",
  "primary-label": "oklch(0.664 0.169 255.4)",
  "destructive-950": "oklch(0.241 0.081 26.9)",
  "destructive-800": "oklch(0.428 0.155 27.2)",
  "destructive-600": "oklch(0.588 0.223 28.0)",
  "destructive-400": "oklch(0.739 0.191 24.7)",
  "destructive-300": "oklch(0.814 0.131 19.8)",
  "destructive-label": "oklch(0.739 0.191 24.7)",
  "success-950": "oklch(0.280 0.072 151.4)",
  "success-800": "oklch(0.472 0.145 149.5)",
  "success-600": "oklch(0.589 0.173 149.7)",
  "success-400": "oklch(0.756 0.171 152.0)",
  "success-300": "oklch(0.921 0.129 151.4)",
  "success-label": "oklch(0.754 0.181 149.0)",
};

export const lightTheme: ThemeVars = {
  ...semanticScaleTokens,
  // ESCADA DE SUPERFICIES — cinco niveis igualmente espacados em luminosidade OKLab
  // (a escala em que distancias iguais parecem iguais). Regra de uso: onde se AGE sobe
  // um nivel, onde se LE desce um, vizinhos nunca no mesmo nivel sem borda. Com passo
  // igual, +1 e -1 sempre dao a mesma diferenca visivel — nenhuma tela depende de
  // avaliacao caso a caso. Ver "Escada de superficies" no padrao visual.
  "level-0": "oklch(1 0 0)",
  "level-1": "var(--surface-fill)",
  "level-2": "oklch(0.930 var(--neutral-chroma) var(--neutral-hue))",
  "level-3": "oklch(0.895 var(--neutral-chroma) var(--neutral-hue))",
  "level-4": "oklch(0.780 var(--neutral-chroma) var(--neutral-hue))",
  background: "var(--level-0)",
  foreground: "var(--neutral-950)",
  card: "var(--level-1)",
  "card-foreground": "var(--neutral-950)",
  popover: "var(--level-1)",
  "popover-foreground": "var(--neutral-950)",
  primary: "var(--primary-600)",
  "primary-foreground": "var(--surface-fill)",
  muted: "var(--level-1)",
  "muted-foreground": "var(--neutral-600)",
  accent: "color-mix(in oklab, var(--level-1) 82%, var(--primary-300) 18%)",
  "accent-foreground": "var(--neutral-950)",
  destructive: "var(--destructive-600)",
  "destructive-foreground": "var(--surface-fill)",
  success: "var(--success-800)",
  "success-foreground": "var(--surface-fill)",
  warning: "oklch(0.77 0.16 70.08)",
  "warning-foreground": "var(--neutral-950)",
  info: "var(--primary)",
  "info-foreground": "var(--primary-foreground)",
  attention: "oklch(0.93 0.2 108.5)",
  "attention-foreground": "var(--neutral-950)",
  input: "var(--level-3)",
  "input-foreground": "var(--neutral-950)",
  border: "var(--level-4)",
  ring: "var(--primary-label)",
  "ring-foreground": "oklch(0.985 0 0)",
  sidebar: "var(--level-1)",
  "sidebar-foreground": "var(--neutral-950)",
  "sidebar-foreground-rgb": "17 24 39",
  "sidebar-primary": "var(--primary-600)",
  "sidebar-primary-foreground": "var(--surface-fill)",
  surface: "var(--level-1)",
  "surface-2": "var(--level-2)",
  "surface-3": "var(--level-3)",
  "radius-sm": "0.25rem",
  "radius-md": "0.5rem",
  "radius-lg": "0.625rem",
  radius: "var(--radius-md)",
  overlay: "oklch(0 0 0 / 0.8)",
  "chart-1": "var(--primary)",
  "chart-2": "var(--success)",
  "chart-3": "var(--attention)",
  "chart-4": "oklch(0.58 0.20 292)",
  "chart-5": "var(--destructive)",
  "sparkline-red": "var(--destructive)",
  "sparkline-orange": "var(--warning)",
  "sparkline-yellow": "oklch(0.75 0.15 90)",
  "sparkline-green": "var(--success)",
  "sparkline-blue": "var(--primary)",
  "sparkline-muted": "var(--muted-foreground)",
};

export const darkTheme: ThemeVars = {
  ...semanticScaleTokens,
  // ESCADA DE SUPERFICIES — cinco niveis igualmente espacados em luminosidade OKLab
  // (a escala em que distancias iguais parecem iguais). Regra de uso: onde se AGE sobe
  // um nivel, onde se LE desce um, vizinhos nunca no mesmo nivel sem borda. Com passo
  // igual, +1 e -1 sempre dao a mesma diferenca visivel — nenhuma tela depende de
  // avaliacao caso a caso. Ver "Escada de superficies" no padrao visual.
  "level-0": "var(--neutral-950)",
  "level-1": "oklch(0.289 var(--neutral-chroma) var(--neutral-hue))",
  "level-2": "oklch(0.369 var(--neutral-chroma) var(--neutral-hue))",
  "level-3": "oklch(0.449 var(--neutral-chroma) var(--neutral-hue))",
  "level-4": "oklch(0.529 var(--neutral-chroma) var(--neutral-hue))",
  background: "var(--level-0)",
  foreground: "var(--surface-fill)",
  card: "var(--level-1)",
  "card-foreground": "var(--surface-fill)",
  popover: "var(--level-1)",
  "popover-foreground": "var(--surface-fill)",
  primary: "var(--primary-600)",
  "primary-foreground": "var(--surface-fill)",
  muted: "var(--level-1)",
  "muted-foreground": "var(--neutral-400)",
  accent: "color-mix(in oklab, var(--level-2) 80%, var(--primary-300) 20%)",
  "accent-foreground": "var(--surface-fill)",
  destructive: "var(--destructive-400)",
  "destructive-foreground": "var(--neutral-950)",
  success: "var(--success-400)",
  "success-foreground": "var(--neutral-950)",
  warning: "oklch(0.58 0.18 55)",
  "warning-foreground": "var(--surface-fill)",
  info: "var(--primary)",
  "info-foreground": "var(--primary-foreground)",
  attention: "oklch(0.78 0.16 95)",
  "attention-foreground": "var(--neutral-950)",
  input: "var(--level-3)",
  "input-foreground": "var(--surface-fill)",
  border: "var(--level-4)",
  ring: "var(--primary-label)",
  "ring-foreground": "var(--surface-fill)",
  sidebar: "var(--level-1)",
  "sidebar-foreground": "var(--surface-fill)",
  "sidebar-foreground-rgb": "250 250 250",
  "sidebar-primary": "var(--primary-400)",
  "sidebar-primary-foreground": "var(--neutral-950)",
  surface: "var(--level-1)",
  "surface-2": "var(--level-2)",
  "surface-3": "var(--level-3)",
  "radius-sm": "0.25rem",
  "radius-md": "0.5rem",
  "radius-lg": "0.625rem",
  radius: "var(--radius-md)",
  overlay: "oklch(0 0 0 / 0.8)",
  "chart-1": "var(--primary)",
  "chart-2": "var(--success)",
  "chart-3": "var(--attention)",
  "chart-4": "oklch(0.74 0.17 302)",
  "chart-5": "var(--destructive)",
  "sparkline-red": "var(--destructive)",
  "sparkline-orange": "var(--warning)",
  "sparkline-yellow": "oklch(0.75 0.15 90)",
  "sparkline-green": "var(--success)",
  "sparkline-blue": "var(--primary)",
  "sparkline-muted": "var(--muted-foreground)",
};
