[connections.supabase]
SUPABASE_URL = "https://oypklljpokxuiowkdgcu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cGtsbGpwb2t4dWlvd2tkZ2N1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNTE3MTI5MCwiZXhwIjoyMDQwNzQ3MjkwfQ.88qQ4BjuqHGEuRkU_FLIOOWpS2-gY1ROAdlRPlEfqV4"